### PR TITLE
Added count of guesses

### PR DESCRIPTION
**Pull request by aloubrehima**
Once the user has guessed correctly, the number of guesses will be displayed

Hey @RichardJThies , please check the change I made and leave a comment. Thank you!

### CODE REVIEW

**Comment by RichardJThies** [comment]
@aloubrehima 
Hey Alou, there does appear to be a variable counting the loops, but there is nothing to print the number of guesses like the issue requests. Please revise with a display to the user.

**Comment by RichardJThies** [comment]
There was another issue on line 48 with a missing format string. But we solved it while on zoom together so there was no record here on this pull request

**Comment by aloubrehima** [comment]
Sure, just took care of it!

**Comment by RichardJThies** [comment]
Checked out the fix, sees to work now!

**Pull request merged**
